GlobalData={};UploadStates={};Code_Initializators=[];GlobalData.filestatematch={};GlobalData.filestatematch.success=[0,1,2,2];GlobalData.filestatematch.warning=[1,1,2,2];GlobalData.filestatematch.error1=[3,3,2,3];GlobalData.filestatematch.error2=[2,2,2,3];GlobalData.UploadInProgressString="";GlobalData.FreeChangeHandler=false;wfu_Check_Browser_Capabilities();
function wfu_Initialize_Consts(consts){if(typeof GlobalData.consts!="undefined")return;GlobalData.consts=new Object;var consts_arr=consts.split(";");var const_arr;for(var i=0;i<consts_arr.length;i++){const_txt=consts_arr[i].split(":");GlobalData.consts[wfu_plugin_decode_string(const_txt[0])]=wfu_plugin_decode_string(const_txt[1])}}
function wfu_Load_Code_Connectors(sid){if(typeof wfu_Code_Objects=="undefined")wfu_Code_Objects={};wfu_Code_Objects[sid]=new wfu_Code_Object(sid);for(var i=0;i<Code_Initializators.length;i++)wfu_Code_Objects[sid].additem(Code_Initializators[i](sid))}
function wfu_Code_Object(sid){this.sid=sid;this.items=[];this._calc_prioritized_list=function(section){var item,list=[],idlist=[],nolist=[],priority;for(var i=0;i<this.items.length;i++){item=this.items[i];if(item[section]){priority=-1;if(item.priority)priority=item.priority;if(item[section].priority)priority=item[section].priority;if(priority>=0){list.push(priority);idlist.push(i)}else nolist.push(i)}}for(var i=1;i<list.length;i++)for(var j=i;j<list.length;j++)if(list[j]<list[i-1]){var temp=list[j];
list[j]=list[i-1];list[i-1]=temp;var temp=idlist[j];idlist[j]=idlist[i-1];idlist[i-1]=temp}return idlist.concat(nolist)};this.additem=function(item){this.items.push(item)};this.apply_filters=function(section,val){if(typeof val=="undefined")return null;var idlist=this._calc_prioritized_list(section);if(idlist.length==0)return val;for(var i=0;i<idlist.length;i++){var item=this.items[idlist[i]];var func=null;if(typeof item[section]=="function")func=item[section];else if(typeof item[section].func=="function")func=
item[section].func;if(func!=null){val=func.apply(this,Array.prototype.slice.call(arguments,1));arguments[1]=val}}return val};this.do_action=function(section){var idlist=this._calc_prioritized_list(section);if(idlist.length==0)return;for(var i=0;i<idlist.length;i++){var item=this.items[idlist[i]];var func=null;if(typeof item[section]=="function")func=item[section];else if(typeof item[section].func=="function")func=item[section].func;if(func!=null)func.apply(this,Array.prototype.slice.call(arguments,
1))}}}function wfu_plugin_load_action(sid){wfu_install_unload_hook();var editbox=document.getElementById("selectsubdiredit_"+sid);if(editbox&&editbox.style.display!="none")wfu_attach_element_handlers(editbox,new Function("wfu_selectsubdiredit_change("+sid+");"))}function wfu_install_unload_hook(){window.onbeforeunload=wfu_unload_hook}function wfu_unload_hook(){if(GlobalData.UploadInProgressString!="")if(GlobalData.UploadInProgressString.trim()!="")return GlobalData.consts.wfu_pageexit_prompt}
function wfu_Check_Browser_Capabilities(){if(typeof wfu_BrowserCaps!="undefined")return;wfu_BrowserCaps=new Object;var xmlhttp=wfu_GetHttpRequestObject();wfu_BrowserCaps.supportsAJAX=xmlhttp!=null;wfu_BrowserCaps.supportsUploadProgress=!!(xmlhttp&&"upload"in xmlhttp&&"onprogress"in xmlhttp.upload);var fd=null;try{var fd=new FormData}catch(e$0){}wfu_BrowserCaps.supportsHTML5=fd!=null;var e=document.createElement("iframe");wfu_BrowserCaps.supportsIFRAME=e!=null;wfu_BrowserCaps.supportsDRAGDROP=window.FileReader?
true:false;wfu_BrowserCaps.supportsAnimation=wfu_check_animation();wfu_BrowserCaps.isSafari=Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")>0}
function wfu_check_animation(){var animation=false,animationstring="animation",keyframeprefix="",domPrefixes="Webkit Moz O ms Khtml".split(" "),pfx="";var elm=document.createElement("DIV");if(elm.style.animationName)animation=true;if(animation===false)for(var i=0;i<domPrefixes.length;i++)if(elm.style[domPrefixes[i]+"AnimationName"]!==undefined){pfx=domPrefixes[i];animationstring=pfx+"Animation";keyframeprefix="-"+pfx.toLowerCase()+"-";animation=true;break}return animation}
function wfu_join_strings(delimeter){var args=[].slice.call(arguments);var str="";var delim="";for(var i=1;i<args.length;i++){if(str==""||args[i]=="")delim="";else delim=delimeter;str+=delim+args[i]}return str}
function wfu_plugin_decode_string(str){var i=0;var newstr="";var num,val;while(i<str.length){num=parseInt(str.substr(i,2),16);if(num<128)val=num;else if(num<224)val=((num&31)<<6)+(parseInt(str.substr(i+=2,2),16)&63);else val=((num&15)<<12)+((parseInt(str.substr(i+=2,2),16)&63)<<6)+(parseInt(str.substr(i+=2,2),16)&63);newstr+=String.fromCharCode(val);i+=2}return newstr}
function wfu_plugin_encode_string(str){var i=0;var newstr="";var hex="";for(i=0;i<str.length;i++){num=str.charCodeAt(i);if(num>=2048)num=((num&16773120|917504)<<4)+((num&4032|8192)<<2)+(num&63|128);else if(num>=128)num=((num&65472|12288)<<2)+(num&63|128);hex=num.toString(16);if(hex.length==1||hex.length==3||hex.length==5)hex="0"+hex;newstr+=hex}return newstr}
function wfu_randomString(len){var chars="0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";var string_length=len;var randomstring="";for(var i=0;i<string_length;i++){var rnum=Math.floor(Math.random()*chars.length);randomstring+=chars.substring(rnum,rnum+1)}return randomstring}function wfu_addEventHandler(obj,evt,handler){if(obj.addEventListener)obj.addEventListener(evt,handler,false);else if(obj.attachEvent)obj.attachEvent("on"+evt,handler);else obj["on"+evt]=handler}
function wfu_attach_element_handlers(item,handler){var elem_events=["DOMAttrModified","textInput","input","change","keypress","paste","focus","propertychange"];for(var i=0;i<elem_events.length;i++)wfu_addEventHandler(item,elem_events[i],handler)}
function wfu_GetHttpRequestObject(){var xhr=null;try{xhr=new XMLHttpRequest}catch(e$1){try{xhr=new ActiveXObject("Msxml2.XMLHTTP")}catch(e2){try{xhr=new ActiveXObject("Microsoft.XMLHTTP")}catch(e){}}}if(xhr==null&&window.createRequest)try{xmlhttp=window.createRequest()}catch(e$2){}return xhr}
function wfu_filedetails_showhide(sid,fileid,show){var item1=document.getElementById("wfu_messageblock_arrow_"+sid+"_"+fileid);var item2=document.getElementById("wfu_messageblock_arrow_"+sid+"_up_"+fileid);var item3=document.getElementById("wfu_messageblock_arrow_"+sid+"_down_"+fileid);var item4=document.getElementById("wfu_messageblock_subheader_"+sid+"_"+fileid);var item5=document.getElementById("wfu_messageblock_header_"+sid+"_state_"+fileid);if(show){item2.style.display="";item3.style.display=
"none";item4.style.display="";item5.value=""}else{item2.style.display="none";item3.style.display="";item4.style.display="none";item5.value="none"}}
function wfu_get_file_ids(sid){var message_table=document.getElementById("wfu_messageblock_"+sid);var next_block=document.getElementById("wfu_messageblock_subheader_"+sid).nextSibling;var prefix="wfu_messageblock_"+sid+"_";var file_ids=[];while(next_block!=null){if(next_block.nodeType===1&&next_block.id.substr(0,prefix.length)==prefix)file_ids.push(next_block.id.substr(next_block.id.lastIndexOf("_")+1));next_block=next_block.nextSibling}return file_ids}
function wfu_get_filelist(sid,include_filearray){include_filearray=typeof include_filearray!=="undefined"?include_filearray:true;var inputfile=document.getElementById("upfile_"+sid);var farr=inputfile.files;if(!farr)if(inputfile.value)farr=[{name:inputfile.value}];else farr=[];if(include_filearray&&typeof inputfile.filearray!=="undefined")farr=inputfile.filearray;return farr}
function wfu_add_files(sid,files){var inputfile=document.getElementById("upfile_"+sid);if(typeof inputfile.filearray=="undefined"){inputfile.filearray=Array();inputfile.filearrayprops=Array()}document.getElementById("uploadform_"+sid).reset();inputfile.filearray.length=inputfile.filearrayprops.length=0;for(var i=0;i<files.length;i++){inputfile.filearray.push(files[i].file);inputfile.filearrayprops.push(files[i].props)}}
function wfu_filedetails_toggle(sid,fileid){var item1=document.getElementById("wfu_messageblock_arrow_"+sid+"_"+fileid);var item2=document.getElementById("wfu_messageblock_arrow_"+sid+"_up_"+fileid);wfu_filedetails_showhide(sid,fileid,item2.style.display=="none")}
function wfu_headerdetails_showhide(sid,show){var item1=document.getElementById("wfu_messageblock_arrow_"+sid);var item2=document.getElementById("wfu_messageblock_arrow_"+sid+"_up");var item3=document.getElementById("wfu_messageblock_arrow_"+sid+"_down");var item4=document.getElementById("wfu_messageblock_subheader_"+sid);var item5=document.getElementById("wfu_messageblock_subheader_"+sid+"_message");var item6=document.getElementById("wfu_messageblock_subheader_"+sid+"_adminmessage");var item7=document.getElementById("wfu_messageblock_header_"+
sid+"_state");var file_ids=wfu_get_file_ids(sid);if(show){item2.style.display="";item3.style.display="none";if(item5.style.display!="none"||item6.style.display!="none")item4.style.display="";item7.value="";for(var i=0;i<file_ids.length;i++){document.getElementById("wfu_messageblock_"+sid+"_"+file_ids[i]).style.display="";document.getElementById("wfu_messageblock_subheader_"+sid+"_"+file_ids[i]).style.display=document.getElementById("wfu_messageblock_header_"+sid+"_state_"+file_ids[i]).value}}else{item2.style.display=
"none";item3.style.display="";item4.style.display="none";item7.value="none";for(var i=0;i<file_ids.length;i++){document.getElementById("wfu_messageblock_"+sid+"_"+file_ids[i]).style.display="none";document.getElementById("wfu_messageblock_subheader_"+sid+"_"+file_ids[i]).style.display="none"}}}
function wfu_headerdetails_toggle(sid){var item1=document.getElementById("wfu_messageblock_arrow_"+sid);var item2=document.getElementById("wfu_messageblock_arrow_"+sid+"_up");wfu_headerdetails_showhide(sid,item2.style.display=="none")}
function wfu_attach_cancel_event(sid,session_token,unique_upload_id,JSONobj){var textbox=document.getElementById("fileName_"+sid);if(!textbox)return;textbox.onkeyup=function(e){if(e.keyCode!=27||!GlobalData[sid]||GlobalData[sid].xhrs.length==0)return;var answer=confirm(GlobalData.consts.cancel_upload_prompt);if(answer==true){var farr=wfu_get_filelist(sid);var firstxhr=[];var filename=[];for(var i=0;i<farr.length;i++){firstxhr.push(null);filename.push(farr[i].name)}for(var i=0;i<GlobalData[sid].xhrs.length;i++){var file_ind=
GlobalData[sid].xhrs[i].file_id-1;if(file_ind>=0&&firstxhr[file_ind]==null)firstxhr[file_ind]=GlobalData[sid].xhrs[i]}if(JSONobj.debugmode=="true")console.log("upload cancelled!");for(var i=0;i<firstxhr.length;i++){if(firstxhr[i]==null){firstxhr[i]=wfu_GetHttpRequestObject();if(firstxhr[i]!=null)wfu_initialize_fileupload_xhr(firstxhr[i],sid,session_token,unique_upload_id,JSONobj,i,filename[i])}if(firstxhr[i]!=-1){var evt={target:{responseText:"force_cancel_code",shortcode_id:sid}};wfu_uploadComplete.call(firstxhr[i],
evt)}}textbox.onkeyup=null}}}function wfu_dettach_cancel_event(sid){var textbox=document.getElementById("fileName_"+sid);if(textbox)textbox.onkeyup=null}
function wfu_selectbutton_changed(sid,usefilearray){if(!wfu_BrowserCaps.supportsAJAX||!wfu_BrowserCaps.supportsHTML5)usefilearray=0;var inputfile=document.getElementById("upfile_"+sid);var farr=wfu_get_filelist(sid,false);if(usefilearray==1){if(typeof inputfile.filearray=="undefined")inputfile.filearray=Array();for(var i=0;i<farr.length;i++)inputfile.filearray.push(farr[i])}else if(typeof inputfile.filearray!="undefined")delete inputfile.filearray;wfu_update_filename_text(sid)}
function wfu_selectbutton_clicked(sid){var message_container=document.getElementById("wordpress_file_upload_message_"+sid);if(message_container)message_container.style.display="none";wfu_reset_message(sid);document.getElementById("upfile_"+sid).value="";var ftext=document.getElementById("fileName_"+sid);if(ftext){ftext.value="";ftext.className="file_input_textbox"}}
function wfu_update_uploadbutton_status(sid){var uploadbutton=document.getElementById("upload_"+sid);if(uploadbutton){var farr=wfu_get_filelist(sid);var status=farr.length>0;status=wfu_Code_Objects[sid].apply_filters("uploadbutton_status",status);uploadbutton.disabled=!status}}
function wfu_update_filename_text(sid){var ftext=document.getElementById("fileName_"+sid);if(ftext){var farr=wfu_get_filelist(sid);var txt="";for(var i=0;i<farr.length;i++){if(txt!="")txt+=", ";txt+=farr[i].name.replace(/c:\\fakepath\\/i,"")}ftext.value=txt}}
function wfu_selectsubdir_check(sid){var sel=document.getElementById("selectsubdir_"+sid);if(!sel)return true;var editbox=document.getElementById("selectsubdiredit_"+sid);var editable=editbox.style.display!="none";if(editable&&sel.selectedIndex>0){editbox.value=sel.value.replace(/^\s+/,"");editbox.className="file_item_clean_match subfolder_autoplus_match";wfu_selectsubdiredit_change(sid)}if(editable)document.getElementById("hiddeninput_"+sid).value=editbox.value;else document.getElementById("hiddeninput_"+
sid).value=sel.selectedIndex;if(!editable&&sel.selectedIndex==0||editable&&(editbox.value==""||editbox.className=="file_item_clean_empty subfolder_autoplus_empty")){if(editable){sel.className="subfolder_autoplus_dropdown_prompt";editbox.value="";GlobalData.FreeChangeHandler=true;editbox.className="file_item_clean_prompt subfolder_autoplus_prompt";GlobalData.FreeChangeHandler=false}else sel.className="file_item_clean_prompt subfolder_dropdown_prompt";return false}else{if(editable)sel.className="subfolder_autoplus_dropdown";
else sel.className="file_item_clean subfolder_dropdown";if(editable&&editbox.className=="file_item_clean_prompt subfolder_autoplus_prompt")editbox.className="file_item_clean subfolder_autoplus";sel.options[0].style.display="none";return true}}
function wfu_selectsubdiredit_enter(sid){var sel=document.getElementById("selectsubdir_"+sid);var editbox=document.getElementById("selectsubdiredit_"+sid);if(editbox.className=="file_item_clean_empty subfolder_autoplus_empty")editbox.value="";sel.className="subfolder_autoplus_dropdown";editbox.className="file_item_clean subfolder_autoplus"}
function wfu_selectsubdiredit_exit(sid){var editbox=document.getElementById("selectsubdiredit_"+sid);if(editbox.value==""){editbox.value=GlobalData.consts.wfu_subdir_typedir;editbox.className="file_item_clean_empty subfolder_autoplus_empty"}}
function wfu_selectsubdiredit_change(sid){if(GlobalData.FreeChangeHandler)return;var sel=document.getElementById("selectsubdir_"+sid);var editbox=document.getElementById("selectsubdiredit_"+sid);if(editbox.style.display=="none")return;if(editbox.className=="file_item_clean_empty subfolder_autoplus_empty"){sel.selectedIndex=0;document.getElementById("hiddeninput_"+sid).value="";return}document.getElementById("hiddeninput_"+sid).value=editbox.value;var found=false,opt;for(var i=1;i<sel.options.length;i++){opt=
sel.options[i].value.replace(/^\s+/,"").toLowerCase();if(editbox.value.length>=3)if(opt.substr(0,editbox.value.length)==editbox.value.toLowerCase())sel.options[i].style.display="block";else sel.options[i].style.display="none";else sel.options[i].style.display="block";if(sel.options[i].value.replace(/^\s+/,"")==editbox.value){sel.selectedIndex=i;editbox.className="file_item_clean_match subfolder_autoplus_match";found=true}}if(!found){sel.selectedIndex=0;editbox.className="file_item_clean subfolder_autoplus"}}
function wfu_selectsubdir_disable_onoff(sid,status){var sel=document.getElementById("selectsubdir_"+sid);if(!sel)return true;var editbox=document.getElementById("selectsubdiredit_"+sid);var editable=editbox.style.display!="none";sel.disabled=status;if(editable)editbox.disabled=status}
function wfu_userdata_focused(obj){var wrapper=document.getElementById(obj.id.replace("_field_","_fieldwrapper_"));if(wrapper.className=="file_userdata_fieldwrapper_required_empty"){wrapper.className="file_userdata_fieldwrapper_required";var msg_hint=document.getElementById(obj.id.replace("_field_","_hint_"));msg_hint.style.display="none"}}function wfu_Redirect(link){window.location=link}function wfu_loadStart(evt){}
function wfu_update_upload_metrics(sid){var totalsize=0;var totalloaded=0;var totaldelta=0;var metrics=Array();var farr=wfu_get_filelist(sid);for(var i=0;i<farr.length;i++)metrics[i]={size:farr[i].size,aborted:false,loaded:0,delta:0};for(var i=0;i<GlobalData[sid].xhrs.length;i++){var file_id=GlobalData[sid].xhrs[i].file_id;if(file_id>0&&GlobalData[sid].xhrs[i].aborted)metrics[file_id-1].aborted=true}for(var i=0;i<GlobalData[sid].xhrs.length;i++){var file_id=GlobalData[sid].xhrs[i].file_id;if(file_id>
0&&!metrics[file_id-1].aborted){metrics[file_id-1].size=Math.max(GlobalData[sid].xhrs[i].totalsize,metrics[file_id-1].size);metrics[file_id-1].loaded+=GlobalData[sid].xhrs[i].sizeloaded;metrics[file_id-1].delta+=Math.max(GlobalData[sid].xhrs[i].deltaloaded,0)}}for(var i=0;i<farr.length;i++){var Gm=GlobalData[sid].metrics[i];if(!metrics[i].aborted&&metrics[i].size>0){Gm.size=metrics[i].size;if(GlobalData.consts.wfu_uploadprogress_mode=="incremental")Gm.progress_pos=Math.min(Gm.progress_pos+(1-Gm.progress_pos)*
metrics[i].delta/(Gm.size-Gm.loaded),1);else Gm.progress_pos=metrics[i].loaded/metrics[i].size;Gm.loaded=metrics[i].loaded;totalsize+=Gm.size;totalloaded+=Gm.loaded;totaldelta+=metrics[i].delta}else{Gm.size=0;Gm.progress_pos=0;Gm.loaded=0}}var Gm=GlobalData[sid].metricstotal;Gm.size=totalsize;if(GlobalData.consts.wfu_uploadprogress_mode=="incremental")Gm.progress_pos=Math.min(Gm.progress_pos+(1-Gm.progress_pos)*totaldelta/(Gm.size-Gm.loaded),1);else Gm.progress_pos=totalloaded/totalsize;Gm.loaded=
totalloaded}
function wfu_uploadProgress(evt,sid,xhrid,debugmode){if(debugmode&&typeof this.xhr=="undefined"){console.log("total="+evt.total+", loaded="+evt.loaded);console.log(evt)}var this_xhr=GlobalData[sid].xhrs[xhrid];if(this_xhr.file_id==0)return;var percentComplete=0;var delta=0;var simplebar=document.getElementById("progressbar_"+sid+"_animation");if(evt.lengthComputable){this_xhr.deltaloaded=evt.loaded-this_xhr.sizeloaded;this_xhr.sizeloaded=evt.loaded;if(this_xhr.size<evt.total&&evt.total>0){delta=evt.total-
this_xhr.size;this_xhr.deltasize+=delta;this_xhr.size+=delta;for(var i=0;i<GlobalData[sid].xhrs.length;i++)if(GlobalData[sid].xhrs[i].file_id==this_xhr.file_id)GlobalData[sid].xhrs[i].totalsize+=delta}wfu_update_upload_metrics(sid);this_xhr.deltaloaded=0;if(simplebar){percentComplete=Math.round(GlobalData[sid].metricstotal.progress_pos*100);simplebar.style.width=percentComplete.toString()+"%"}}else if(simplebar)simplebar.style.width="0%"}
function wfu_notify_WPFilebase(params_index,session_token){var xhr=wfu_GetHttpRequestObject();if(xhr==null){var i=document.createElement("iframe");i.style.display="none";i.src=GlobalData.consts.ajax_url+"?action=wfu_ajax_action_notify_wpfilebase&params_index="+params_index+"&session_token="+session_token;document.body.appendChild(i);return}var url=GlobalData.consts.ajax_url;params=new Array(3);params[0]=new Array(2);params[0][0]="action";params[0][1]="wfu_ajax_action_notify_wpfilebase";params[1]=
new Array(2);params[1][0]="params_index";params[1][1]=params_index;params[2]=new Array(2);params[2][0]="session_token";params[2][1]=session_token;var parameters="";for(var i=0;i<params.length;i++)parameters+=(i>0?"&":"")+params[i][0]+"="+encodeURI(params[i][1]);xhr.open("POST",url,true);xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhr.onreadystatechange=function(){};xhr.send(parameters)}
function wfu_send_email_notification(sid,unique_id,params_index,session_token,notify_only_filename_list,notify_target_path_list,notify_attachment_list,debugmode,is_admin){var xhr=wfu_GetHttpRequestObject();if(xhr==null)return;var url=GlobalData.consts.ajax_url;var userdata_count=wfu_get_userdata_count(sid);params=new Array(7+userdata_count);params[0]=new Array(2);params[0][0]="action";params[0][1]="wfu_ajax_action_send_email_notification";params[1]=new Array(2);params[1][0]="params_index";params[1][1]=
params_index;params[2]=new Array(2);params[2][0]="session_token";params[2][1]=session_token;params[3]=new Array(2);params[3][0]="only_filename_list";params[3][1]=notify_only_filename_list;params[4]=new Array(2);params[4][0]="target_path_list";params[4][1]=notify_target_path_list;params[5]=new Array(2);params[5][0]="attachment_list";params[5][1]=notify_attachment_list;params[6]=new Array(2);params[6][0]="uniqueuploadid_"+sid;params[6][1]=unique_id;for(var i=0;i<userdata_count;i++){params[7+i]=new Array(2);
params[7+i][0]="userdata_"+i;params[7+i][1]=wfu_plugin_encode_string(document.getElementById("hiddeninput_"+sid+"_userdata_"+i).value)}var parameters="";for(var i=0;i<params.length;i++)parameters+=(i>0?"&":"")+params[i][0]+"="+encodeURI(params[i][1]);wfu_initialize_fileupload_xhr(xhr,sid,session_token,unique_id,{params_index:params_index,debugmode:debugmode,is_admin:is_admin,fail_colors:GlobalData.consts.fail_colors,error_header:""},-1,"");xhr.error_adminmessage_unknown="";xhr.open("POST",url,true);
xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhr.addEventListener("load",wfu_uploadComplete,false);xhr.addEventListener("error",wfu_uploadFailed,false);xhr.addEventListener("abort",wfu_uploadCanceled,false);xhr.send(parameters)}
function wfu_format_debug_data(data,title){output='<label class="file_messageblock_subheader_debugmessage_label">';output+="Debug Data"+title;output+="</label>";output+='<div class="file_messageblock_subheader_debugmessage_container">';output+=data;output+="</div>";return output}
function wfu_uploadComplete(evt){var d=new Date;var sid=this.shortcode_id;var i=this.file_id;var last=false;var js_script_enc="";var upload_params="";var safe_params="";var file_status="unknown";var uploaded_file_props="";var debug_data="";var success_txt="wfu_fileupload_success:";this.loading=false;this.end_time=d.getTime();var txt=evt.target.responseText;var result_data=txt;var error_code="error";if(txt!=-1){if(txt.indexOf("force_errorabort_code")>-1){error_code="errorabort";txt=txt.replace("force_errorabort_code",
"")}if(txt.indexOf("force_cancel_code")>-1){error_code="errorcancel";txt=txt.replace("force_cancel_code","")}}if(txt!=-1){var pos=txt.indexOf(success_txt);if(pos>-1){if(this.debugmode=="true")debug_data=txt.substr(0,pos);result_data=txt.substr(pos+success_txt.length);pos=result_data.indexOf(":");js_script_enc=result_data.substr(0,pos);result_data=result_data.substr(pos+1);pos=result_data.indexOf(":");safe_params=result_data.substr(0,pos);upload_params=result_data.substr(pos+1)}if(debug_data!=""){var title=
"";if(this.requesttype=="fileupload")title=" - File: "+this.file_id;else if(this.requesttype=="email")title=" - Email Notification";debug_data=wfu_format_debug_data(debug_data,title)}if(safe_params!=""){var safe_parts=safe_params.split(";");if(parseInt(safe_parts[2])==1){var filedata=safe_parts[3].split(",");file_status=wfu_plugin_decode_string(filedata[0]);uploaded_file_props=filedata[4]}}}if(upload_params==""||safe_params==""){var error_colors=this.fail_colors.split(",");var Params=wfu_Initialize_Params();
Params.general.shortcode_id=sid;Params.general.unique_id=this.unique_id;Params.general.state=7;Params.general.files_count=this.requesttype=="fileupload"?1:0;Params.general.upload_finish_time=this.finish_time;if(error_code!="errorcancel"){Params.general.fail_message=GlobalData.consts.message_unknown;Params.general.fail_admin_message=wfu_join_strings("<br />",this.error_adminmessage_unknown,this.requesttype+":"+result_data)}else{Params.general.fail_message=GlobalData.consts.file_cancelled;Params.general.fail_admin_message=
""}if(Params.general.files_count>0){Params[0]={};Params[0]["color"]=error_colors[0];Params[0]["bgcolor"]=error_colors[1];Params[0]["borcolor"]=error_colors[2];Params[0]["message_type"]=error_code;file_status=error_code;Params[0]["header"]=this.error_message_header;Params[0]["message"]=GlobalData.consts.message_timelimit;Params[0]["admin_messages"]=this.is_admin=="true"?GlobalData.consts.message_admin_timelimit:""}else Params.general.admin_messages.other=this.is_admin=="true"?GlobalData.consts.message_admin_timelimit:
"";if(Params.general.upload_finish_time>0)if(d.getTime()<Params.general.upload_finish_time)if(Params.general.files_count>0){Params[0]["message"]=Params.general.fail_message;Params[0]["admin_messages"]=this.is_admin=="true"?Params.general.fail_admin_message:""}else Params.general.admin_messages.other=this.is_admin=="true"?Params.general.fail_admin_message:""}if(upload_params==""||safe_params=="")last=wfu_ProcessUploadComplete(sid,this.file_id,Params,this.unique_id,this.params_index,this.session_token,
"",[this.debugmode,debug_data,this.is_admin],this.requesttype,"");else last=wfu_ProcessUploadComplete(sid,this.file_id,upload_params,this.unique_id,this.params_index,this.session_token,safe_params,[this.debugmode,debug_data,this.is_admin],this.requesttype,js_script_enc);if(last){wfu_dettach_cancel_event(sid);wfu_unlock_upload(sid);wfu_hide_simple_progressbar(sid);wfu_clear(sid)}if(evt.target.return_status)return file_status}
function wfu_ProcessUploadComplete(sid,file_id,upload_params,unique_id,params_index,session_token,safe_output,debug_data,request_type,js_script_enc){if(!sid||sid<0)return;if(upload_params==null||upload_params=="")return;if(unique_id=="")return;if(unique_id!="no-ajax"&&!GlobalData[sid])return;var do_redirect=false;if(typeof upload_params==="string"){upload_params=wfu_plugin_decode_string(upload_params.replace(/^\s+|\s+$/g,""));var Params=null;try{Params=JSON.parse(upload_params)}catch(e){}if(Params==
null){var safe_parts=safe_output.split(";");Params=wfu_Initialize_Params();Params.general.shortcode_id=sid;Params.general.unique_id=unique_id;Params.general.state=safe_parts[0];if(Params.general.state==4)Params.general.state++;var default_colors=safe_parts[1].split(",");var filedata="";var error_jsonparse_filemessage=GlobalData.consts.jsonparse_filemessage;var error_jsonparse_message=GlobalData.consts.jsonparse_message;var error_jsonparse_adminmessage=GlobalData.consts.jsonparse_adminmessage;Params.general.files_count=
parseInt(safe_parts[2]);for(var i=0;i<Params.general.files_count;i++){Params[i]={};Params[i]["color"]=default_colors[0];Params[i]["bgcolor"]=default_colors[1];Params[i]["borcolor"]=default_colors[2];filedata=safe_parts[i+3].split(",");Params[i]["message_type"]=wfu_plugin_decode_string(filedata[0]);Params[i]["header"]=wfu_plugin_decode_string(filedata[1]);if(Params[i]["message_type"]=="success"){Params[i]["header"]+=error_jsonparse_filemessage;Params[i]["message_type"]="warning"}Params[i]["message"]=
wfu_join_strings("<br />",error_jsonparse_message,wfu_plugin_decode_string(filedata[2]));Params[i]["admin_messages"]=wfu_join_strings("<br />",error_jsonparse_adminmessage,wfu_plugin_decode_string(filedata[3]))}}}else if(typeof upload_params==="object")var Params=upload_params;else return;i=0;while(Params[i]){if(Params[i].message_type)if(Params[i].message_type.substr(0,5)=="error")Params[i].message_type=Params[i].message_type.substr(0,5);i++}var message_table=document.getElementById("wfu_messageblock_"+
sid);var UploadStates_Ok=true;if(!UploadStates[sid]&&message_table){var upload_states=document.getElementById("wfu_messageblock_header_"+sid+"_states").value;upload_states=wfu_plugin_decode_string(upload_states.replace(/^\s+|\s+$/g,""));UploadStates[sid]=null;try{UploadStates[sid]=JSON.parse(upload_states)}catch(e$3){}if(UploadStates[sid]==null)UploadStates_Ok=false}if(!GlobalData[sid])GlobalData[sid]=Object();var G=GlobalData[sid];if(unique_id=="no-ajax"){G.last=false;G.unique_id="";G.files_count=
Params.general.files_count;if(Params.general.state==0)Params.general.files_count=0;G.files_processed=Params.general.files_count;if(UploadStates_Ok)G.upload_state=Params.general.state;else G.upload_state=10;G.message=Params.general.message;G.update_wpfilebase=Params.general.update_wpfilebase;G.redirect_link=Params.general.redirect_link;G.notify_only_filename_list="";G.notify_target_path_list="";G.notify_attachment_list="";G.admin_messages={};G.admin_messages.wpfilebase=Params.general.admin_messages.wpfilebase;
G.admin_messages.notify=Params.general.admin_messages.notify;G.admin_messages.redirect=Params.general.admin_messages.redirect;G.admin_messages.debug=debug_data[1];G.admin_messages.other=Params.general.admin_messages.other;G.errors={};G.errors.wpfilebase=Params.general.errors.wpfilebase;G.errors.notify=Params.general.errors.notify;G.errors.redirect=Params.general.errors.redirect;G.current_size=0;G.total_size=0}else{if(G.unique_id==""||G.unique_id!=unique_id||G.unique_id!=Params.general.unique_id)return;
if(G.last)return;if(Params.general.files_count==0&&Params[0])if(Params[0].message_type=="error")Params.general.files_count=1;var file_status="";for(var i=0;i<Params.general.files_count;i++){if(Params[i].message_type=="error"&&G.files_processed==0)file_status="error1";else if(Params[i].message_type=="error"&&G.files_processed>0)file_status="error2";else file_status=Params[i].message_type;G.upload_state=GlobalData.filestatematch[file_status][G.upload_state]}if(!UploadStates_Ok)G.upload_state=10;G.files_processed+=
Params.general.files_count;G.message=wfu_join_strings("<br />",G.message,Params.general.message);if(G.update_wpfilebase=="")G.update_wpfilebase=Params.general.update_wpfilebase;if(!request_type||request_type&&request_type!="email")G.redirect_link=Params.general.redirect_link;G.notify_only_filename_list=wfu_join_strings(", ",G.notify_only_filename_list,Params.general.notify_only_filename_list);G.notify_target_path_list=wfu_join_strings(", ",G.notify_target_path_list,Params.general.notify_target_path_list);
G.notify_attachment_list=wfu_join_strings(",",G.notify_attachment_list,Params.general.notify_attachment_list);G.admin_messages.debug=wfu_join_strings("<br />",G.admin_messages.debug,debug_data[1]);G.admin_messages.other=wfu_join_strings("<br />",G.admin_messages.other,Params.general.admin_messages.other);if(G.admin_messages.wpfilebase=="")G.admin_messages.wpfilebase=Params.general.admin_messages.wpfilebase;if(G.admin_messages.notify=="")G.admin_messages.notify=Params.general.admin_messages.notify;
if(G.admin_messages.redirect=="")G.admin_messages.redirect=Params.general.admin_messages.redirect;if(G.errors.wpfilebase=="")G.errors.wpfilebase=Params.general.errors.wpfilebase;if(G.errors.notify=="")G.errors.notify=Params.general.errors.notify;if(G.errors.redirect=="")G.errors.redirect=Params.general.errors.redirect}if(G.files_processed==G.files_count){G.last=true;if(G.update_wpfilebase!=""){G.admin_messages.wpfilebase="";wfu_notify_WPFilebase(params_index,session_token)}if(G.notify_only_filename_list!=
""){G.admin_messages.notify="";wfu_send_email_notification(sid,unique_id,params_index,session_token,G.notify_only_filename_list,G.notify_target_path_list,G.notify_attachment_list,debug_data[0],debug_data[2]);G.last=false;G.notify_only_filename_list=""}if(G.last){if(unique_id!="no-ajax")wfu_notify_server_upload_ended(sid,unique_id,params_index,session_token);GlobalData.UploadInProgressString=GlobalData.UploadInProgressString.replace(new RegExp("\\["+unique_id+"\\]","g"),"")}if(G.errors.redirect!="")G.redirect_link=
"";if(G.redirect_link!=""&&G.last&&GlobalData.UploadInProgressString.trim()==""){G.upload_state=11;do_redirect=true}}var nonadmin_message=G.message;var admin_message=wfu_join_strings("<br />",G.admin_messages.other,G.admin_messages.wpfilebase,G.admin_messages.notify,G.admin_messages.redirect,G.admin_messages.debug);if(!UploadStates_Ok){var error_jsonparse_headermessage=GlobalData.consts.jsonparse_headermessage;var error_jsonparse_headeradminmessage=GlobalData.consts.jsonparse_headeradminmessage;nonadmin_message=
wfu_join_strings("<br />",error_jsonparse_headermessage,nonadmin_message);admin_message=wfu_join_strings("<br />",error_jsonparse_headeradminmessage,admin_message)}if(G.last){if(G.files_count==0&&G.upload_state!=12)G.upload_state=8;else if(G.upload_state<4)G.upload_state+=4;var admin_messages_exist=G.admin_messages.wpfilebase!=""||G.admin_messages.notify!=""||G.admin_messages.redirect!=""||G.admin_messages.other!="";if(G.upload_state==4&&admin_message!="")G.upload_state++;else if(G.upload_state==
5&&!admin_message==""&&nonadmin_message=="")G.upload_state--}if(message_table){var subheader_state=document.getElementById("wfu_messageblock_header_"+sid+"_state");var single_file_shown=G.files_count==1&&nonadmin_message==""&&admin_message==""&&G.last&&!do_redirect;if(single_file_shown)document.getElementById("wfu_messageblock_header_"+sid).style.display="none";else{document.getElementById("wfu_messageblock_header_"+sid).style.display="";var header_container=document.getElementById("wfu_messageblock_header_"+
sid+"_container");if(UploadStates_Ok){var suffix="";if(G.files_count==1&&(G.upload_state==5||G.upload_state==7))suffix="_singlefile";header_container.innerHTML=UploadStates[sid]["State"+G.upload_state+suffix]}else{header_container.innerHTML="";var safe_container=document.getElementById("wfu_messageblock_header_"+sid+"_safecontainer");header_container.innerHTML=safe_container.innerHTML.replace(/_safe/g,"")}var subheader_show=false;if(nonadmin_message!=""){document.getElementById("wfu_messageblock_subheader_"+
sid+"_message").style.display="";document.getElementById("wfu_messageblock_subheader_"+sid+"_messagelabel").innerHTML=nonadmin_message;subheader_show=true}else document.getElementById("wfu_messageblock_subheader_"+sid+"_message").style.display="none";if(admin_message!=""){document.getElementById("wfu_messageblock_subheader_"+sid+"_adminmessage").style.display="";document.getElementById("wfu_messageblock_subheader_"+sid+"_adminmessagelabel").innerHTML=admin_message;subheader_show=true}else document.getElementById("wfu_messageblock_subheader_"+
sid+"_adminmessage").style.display="none";if(subheader_show)document.getElementById("wfu_messageblock_subheader_"+sid).style.display=subheader_state.value;else document.getElementById("wfu_messageblock_subheader_"+sid).style.display="none";if(subheader_show||G.files_processed>0){header_container.colSpan=2;document.getElementById("wfu_messageblock_arrow_"+sid).style.display=""}else{document.getElementById("wfu_messageblock_arrow_"+sid).style.display="none";header_container.colSpan=3}}var next_block=
document.getElementById("wfu_messageblock_subheader_"+sid);var next_block_id=0;var file_block=null;var file_template_container=document.getElementById("wfu_messageblock_"+sid+"_filetemplate");var file_contents="";var door=document.getElementById("wfu_messageblock_"+sid+"_door");var ii=0;var headerspan=1;var subheaderspan=2;var file_template=wfu_plugin_decode_string(file_template_container.value.replace(/^\s+|\s+$/g,""));for(var i=0;i<Params.general.files_count;i++){ii=i+file_id;file_contents=file_template.replace(/\[file_id\]/g,
ii);file_contents=file_contents.replace(/\[filenumber_display\]/g,"");file_contents=file_contents.replace(/\[fileheader_color\]/g,Params[i].color);file_contents=file_contents.replace(/\[fileheader_bgcolor\]/g,Params[i].bgcolor);file_contents=file_contents.replace(/\[fileheader_borcolor\]/g,Params[i].borcolor);file_contents=file_contents.replace(/\[fileheader_message\]/g,Params[i].header);file_contents=file_contents.replace(/\[filesubheadermessage_display\]/g,'style="display:none;"');file_contents=
file_contents.replace(/\[filesubheader_message\]/g,Params[i].message);file_contents=file_contents.replace(/\[filesubheaderadminmessage_display\]/g,'style="display:none;"');file_contents=file_contents.replace(/\[filesubheader_adminmessage\]/g,Params[i].admin_messages);file_contents="<table><tbody>"+file_contents+"</tbody></table>";door.innerHTML=file_contents;headerspan=1;subheaderspan=2;subheader_show=false;file_block=document.getElementById("wfu_messageblock_"+sid+"_"+ii);if(G.files_count==1){document.getElementById("wfu_messageblock_"+
sid+"_filenumber_"+ii).style.display="none";document.getElementById("wfu_messageblock_subheader_"+sid+"_fileempty_"+ii).style.display="none";if(single_file_shown)file_block.style.display="";else file_block.style.display=subheader_state.value;headerspan++;subheaderspan++}else file_block.style.display=subheader_state.value;if(Params[i].message!=""){document.getElementById("wfu_messageblock_subheader_"+sid+"_message_"+ii).style.display="";subheader_show=true}if(Params[i].admin_messages!=""){document.getElementById("wfu_messageblock_subheader_"+
sid+"_adminmessage_"+ii).style.display="";subheader_show=true}if(!subheader_show){document.getElementById("wfu_messageblock_arrow_"+sid+"_"+ii).style.display="none";headerspan++}document.getElementById("wfu_messageblock_header_"+sid+"_container_"+ii).colSpan=headerspan;document.getElementById("wfu_messageblock_subheader_"+sid+"_container_"+ii).colSpan=subheaderspan;while(next_block_id<ii){next_block=next_block.nextSibling;if(next_block==null)break;if(next_block.nodeType===1)next_block_id=next_block.id.substr(next_block.id.lastIndexOf("_")+
1)}message_table.tBodies[0].insertBefore(file_block,next_block);next_block=file_block.nextSibling;file_block=document.getElementById("wfu_messageblock_subheader_"+sid+"_"+ii);message_table.tBodies[0].insertBefore(file_block,next_block);next_block=file_block;next_block_id=ii}if(single_file_shown)document.getElementById("wfu_messageblock_"+sid+"_1").style.display="";message_table.style.display="";document.getElementById("wordpress_file_upload_message_"+sid).style.display=""}if(js_script_enc)eval(wfu_plugin_decode_string(js_script_enc));
if(do_redirect)wfu_Redirect(G.redirect_link);return G.last}function wfu_uploadFailed(evt,debugmode){if(debugmode){console.log("failure report following");console.log(evt)}var xhr=evt.target;var new_evt={target:{responseText:"",shortcode_id:xhr.shortcode_id}};wfu_uploadComplete.call(xhr,new_evt)}function wfu_uploadCanceled(evt){}
function wfu_notify_server_upload_ended(sid,unique_id,params_index,session_token){var xhr=wfu_GetHttpRequestObject();if(xhr==null)return;var url=GlobalData.consts.ajax_url;params=new Array(6);params[0]=new Array(2);params[0][0]="action";params[0][1]="wfu_ajax_action";params[1]=new Array(2);params[1][0]="wfu_uploader_nonce";params[1][1]=document.getElementById("wfu_uploader_nonce_"+sid).value;params[2]=new Array(2);params[2][0]="uniqueuploadid_"+sid;params[2][1]=unique_id;params[3]=new Array(2);params[3][0]=
"params_index";params[3][1]=params_index;params[4]=new Array(2);params[4][0]="session_token";params[4][1]=session_token;params[5]=new Array(2);params[5][0]="upload_finished";params[5][1]=1;var parameters="";for(var i=0;i<params.length;i++)parameters+=(i>0?"&":"")+params[i][0]+"="+encodeURI(params[i][1]);xhr.open("POST",url,true);xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhr.onreadystatechange=function(){if(xhr.readyState==4)if(xhr.status==200)wfu_Code_Objects[sid].do_action("after_upload",
xhr.responseText)};xhr.send(parameters)}
function wfu_Initialize_Params(){var params={};params.version="full";params.general={};params.general.shortcode_id=0;params.general.unique_id="";params.general.state=0;params.general.files_count=0;params.general.update_wpfilebase="";params.general.redirect_link="";params.general.upload_finish_time=0;params.general.message="";params.general.message_type="";params.general.admin_messages={};params.general.admin_messages.wpfilebase="";params.general.admin_messages.notify="";params.general.admin_messages.redirect=
"";params.general.admin_messages.other="";params.general.errors={};params.general.errors.wpfilebase="";params.general.errors.notify="";params.general.errors.redirect="";params.general.color="";params.general.bgcolor="";params.general.borcolor="";params.general.notify_only_filename_list="";params.general.notify_target_path_list="";params.general.notify_attachment_list="";params.general.fail_message="";params.general.fail_admin_message="";return params}
function wfu_redirect_to_classic(sid,session_token,flag,adminerrorcode){if(wfu_filesselected(sid)==0)return;if(!wfu_selectsubdir_check(sid))return;if(!wfu_check_required_userdata(sid,true))return;if(!wfu_Code_Objects[sid].apply_filters("pre_start_check",true))return;wfu_redirect_to_classic_cont(sid,session_token,flag,adminerrorcode)}
function wfu_redirect_to_classic_cont(sid,session_token,flag,adminerrorcode){var process_function=function(responseText){var txt_value="";var success_txt="wfu_askserver_success:";var error_txt="wfu_askserver_error:";var pos_success=responseText.indexOf(success_txt);var pos_error=responseText.indexOf(error_txt);if(pos_success>-1){txt_value=responseText.substr(pos_success+success_txt.length);wfu_Code_Objects[sid].do_action("askserver_success",txt_value,"no-ajax");var Params=wfu_Initialize_Params();
Params.general.shortcode_id=sid;Params.general.unique_id="";Params.general.files_count=wfu_filesselected(sid);wfu_ProcessUploadComplete(sid,0,Params,"no-ajax","",session_token,"",["false","","false"]);if(flag==1){var suffice="";document.getElementById("upfile_"+sid).name="uploadedfile_"+sid+"_redirected"+suffice}if(adminerrorcode>0)document.getElementById("adminerrorcodes_"+sid).value=adminerrorcode;else document.getElementById("adminerrorcodes_"+sid).value="";document.getElementById("upfile_"+sid).disabled=
false;document.getElementById("uniqueuploadid_"+sid).value=unique_id;document.getElementById("uploadform_"+sid).submit()}else if(pos_error>-1){txt_value=responseText.substr(pos_error+error_txt.length);wfu_unlock_upload(sid);wfu_Code_Objects[sid].do_action("askserver_error",txt_value)}};var unique_id=wfu_randomString(10);wfu_lock_upload(sid);wfu_Code_Objects[sid].do_action("pre_start");var pass_params="";var params_obj=wfu_Code_Objects[sid].apply_filters("askserver_pass_params",{});for(var prop in params_obj)if(params_obj.hasOwnProperty(prop))pass_params+=
"&"+prop+"="+params_obj[prop];var d=new Date;var url=GlobalData.consts.ajax_url+"?action=wfu_ajax_action_ask_server&wfu_uploader_nonce="+document.getElementById("wfu_uploader_nonce_"+sid).value+"&sid="+sid+"&unique_id="+unique_id+"&start_time="+d.getTime()+"&session_token="+session_token+pass_params;var xmlhttp=wfu_GetHttpRequestObject();if(xmlhttp==null){var i=document.createElement("iframe");if(i){i.style.display="none";i.src=url;document.body.appendChild(i);i.onload=function(){process_function(i.contentDocument.body.innerHTML)};
return}else{wfu_Code_Objects[sid].do_action("not_supported");return}}xmlhttp.open("GET",url,true);xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4)if(xmlhttp.status==200)process_function(xmlhttp.responseText);else{alert(GlobalData.consts.remoteserver_noresult);wfu_Code_Objects[sid].do_action("askserver_noresult")}};xmlhttp.send(null)}
Code_Initializators[Code_Initializators.length]=function(sid){var CBUV_Code_Objects={};CBUV_Code_Objects.pre_start_ask_server=function(attr,has_filters){if(attr)return attr;var sid=this.sid;return has_filters=="true"};CBUV_Code_Objects.askserver_pass_params=function(params){var sid=this.sid;var farr=wfu_get_filelist(sid);var filenames="";var filesizes="";for(var i=0;i<farr.length;i++){if(i>0){filenames+=";";filesizes+=";"}filenames+=wfu_plugin_encode_string(farr[i].name);filesizes+=farr[i].size}params.filenames=
filenames;params.filesizes=filesizes;return params};CBUV_Code_Objects.askserver_success=function(response,mode){var sid=this.sid;var upload_status="success";var txt_match=response.match(/CBUVJS\[(.*?)\]/);var txt_header=txt_match?typeof txt_match[1]!="undefined"?txt_match[1]:"":"";if(txt_header!="")eval(txt_header)};CBUV_Code_Objects.askserver_error=function(response,mode){var sid=this.sid;var upload_status="error";var txt_match=response.match(/CBUVJS\[(.*?)\]/);var txt_header=txt_match?typeof txt_match[1]!=
"undefined"?txt_match[1]:"":"";if(txt_header!="")eval(txt_header);txt_match=response.match(/CBUV\[(.*?)\]/);txt_header=txt_match?typeof txt_match[1]!="undefined"?txt_match[1]:"":"";if(txt_header!=""){var Params=wfu_Initialize_Params();Params.general.shortcode_id=sid;Params.general.message=txt_header;Params.general.state=12;wfu_ProcessUploadComplete(sid,0,Params,"no-ajax","","","",["false","","false"]);wfu_clear(sid)}};CBUV_Code_Objects.after_upload=function(response){var sid=this.sid;var txt_match=
response.match(/CBUVJS\[(.*?)\]/);var txt_header=txt_match?typeof txt_match[1]!="undefined"?txt_match[1]:"":"";if(txt_header!="")eval(txt_header)};return CBUV_Code_Objects};function wfu_filesselected(sid){var ftext=document.getElementById("fileName_"+sid);var farr=wfu_get_filelist(sid);if(farr.length==0)if(ftext){ftext.value=GlobalData.consts.nofilemessage;ftext.className="file_input_textbox_nofile"}return farr.length}
function wfu_check_required_userdata(sid,prompt){var userdata_count=wfu_get_userdata_count(sid);var req_empty=false;for(var i=0;i<userdata_count;i++){var msg_hid=document.getElementById("hiddeninput_"+sid+"_userdata_"+i);var wrapper=document.getElementById("userdata_"+sid+"_fieldwrapper_"+i);var field=document.getElementById("userdata_"+sid+"_field_"+i);var msg_cont=document.getElementById("userdata_"+sid+"_"+i);var msg_hint=document.getElementById("userdata_"+sid+"_hint_"+i);msg_hid.value=window["userdata_"+
sid+"_codes_"+i].value(field);var props={hintposition:"none"};var props_raw=document.getElementById("userdata_"+sid+"_props_"+i).value.split("|");for(var j=0;j<props_raw.length;j++)if(props_raw[j].substr(0,2)=="p:")props.hintposition=props_raw[j].substr(2);var res="";if(wrapper.className.substr(0,35)=="file_userdata_fieldwrapper_required")res=window["userdata_"+sid+"_codes_"+i].empty(msg_hid);if(res===""&&window["userdata_"+sid+"_codes_"+i].validate)res=window["userdata_"+sid+"_codes_"+i].validate(msg_hid);
if(res!==""){if(prompt)if(props.hintposition=="none")msg_hint.className="file_userdata_hint_none";else{wrapper.className="file_userdata_fieldwrapper_required_empty";var cont_rect=msg_cont.getBoundingClientRect();var msg_rect=wrapper.getBoundingClientRect();if(props.hintposition=="inline"){msg_hint.className="file_userdata_hint_inline";msg_hint.style.left=parseInt(msg_rect.left-cont_rect.left)+"px";msg_hint.style.top=parseInt(msg_rect.top-cont_rect.top)+"px";msg_hint.style.right=parseInt(cont_rect.right-
msg_rect.right)+"px";msg_hint.style.bottom=parseInt(cont_rect.bottom-msg_rect.bottom)+"px"}else if(props.hintposition=="top"){msg_hint.className="file_userdata_hint_top";msg_hint.style.left=parseInt(msg_rect.left-cont_rect.left)+"px";msg_hint.style.bottom=parseInt(cont_rect.bottom-msg_rect.top)+"px"}else if(props.hintposition=="right"){msg_hint.className="file_userdata_hint_right";msg_hint.style.left=parseInt(msg_rect.right-cont_rect.left)+"px";msg_hint.style.top=parseInt(msg_rect.top-cont_rect.top)+
"px"}else if(props.hintposition=="bottom"){msg_hint.className="file_userdata_hint_bottom";msg_hint.style.left=parseInt(msg_rect.left-cont_rect.left)+"px";msg_hint.style.top=parseInt(msg_rect.bottom-cont_rect.top)+"px"}else if(props.hintposition=="left"){msg_hint.className="file_userdata_hint_left";msg_hint.style.right=parseInt(cont_rect.right-msg_rect.left)+"px";msg_hint.style.top=parseInt(msg_rect.top-cont_rect.top)+"px"}msg_hint.innerHTML=res;msg_hint.style.display="block"}req_empty=true}}return!req_empty}
function wfu_HTML5UploadFile(sid,JSONtext,session_token){if(!wfu_BrowserCaps.supportsAJAX){wfu_redirect_to_classic(sid,session_token,1,1);return}if(!wfu_BrowserCaps.supportsHTML5){wfu_redirect_to_classic(sid,session_token,1,2);return}JSONtext=wfu_plugin_decode_string(JSONtext.replace(/^\s+|\s+$/g,""));var JSONobj=null;try{JSONobj=JSON.parse(JSONtext)}catch(e){}if(JSONobj==null){wfu_redirect_to_classic(sid,session_token,1,3);return}var xhr=wfu_GetHttpRequestObject();if(xhr==null)return;var numfiles=
wfu_filesselected(sid);if(numfiles==0)return;var uploadbutton=document.getElementById("upload_"+sid);var single_file_operation=!uploadbutton;if(!wfu_selectsubdir_check(sid)){if(single_file_operation)wfu_clear_files(sid);return}var numpasses=numfiles;numpasses+=numpasses;if(!wfu_check_required_userdata(sid,true)){if(single_file_operation)wfu_clear_files(sid);return}if(!wfu_Code_Objects[sid].apply_filters("pre_start_check",true))return;var unique_upload_id=wfu_randomString(10);wfu_lock_upload(sid);
wfu_Code_Objects[sid].do_action("pre_start");if(!wfu_Code_Objects[sid].apply_filters("pre_start_ask_server",false,JSONobj.has_filters))wfu_HTML5UploadFile_cont(sid,JSONobj,session_token,unique_upload_id);else{var url=GlobalData.consts.ajax_url;params=new Array(5);params[0]=new Array(2);params[0][0]="action";params[0][1]="wfu_ajax_action_ask_server";params[1]=new Array(2);params[1][0]="session_token";params[1][1]=session_token;params[2]=new Array(2);params[2][0]="sid";params[2][1]=sid;params[3]=new Array(2);
params[3][0]="unique_id";params[3][1]=unique_upload_id;params[4]=new Array(2);params[4][0]="wfu_uploader_nonce";params[4][1]=document.getElementById("wfu_uploader_nonce_"+sid).value;var params_obj=wfu_Code_Objects[sid].apply_filters("askserver_pass_params",{});for(var prop in params_obj)if(params_obj.hasOwnProperty(prop))params.push([prop,params_obj[prop]]);var parameters="";for(var i=0;i<params.length;i++)parameters+=(i>0?"&":"")+params[i][0]+"="+encodeURI(params[i][1]);xhr.open("POST",url,true);
xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhr.onreadystatechange=function(){if(xhr.readyState==4)if(xhr.status==200){var txt=xhr.responseText;var txt_value="";var success_txt="wfu_askserver_success:";var error_txt="wfu_askserver_error:";var pos_success=txt.indexOf(success_txt);var pos_error=txt.indexOf(error_txt);var pos=-1;if(pos_success>-1){txt_value=txt.substr(pos_success+success_txt.length);wfu_Code_Objects[sid].do_action("askserver_success",txt_value,"ajax");wfu_HTML5UploadFile_cont(sid,
JSONobj,session_token,unique_upload_id)}else if(pos_error>-1){txt_value=txt.substr(pos_error+error_txt.length);wfu_unlock_upload(sid);wfu_Code_Objects[sid].do_action("askserver_error",txt_value)}}else{alert(GlobalData.consts.remoteserver_noresult);wfu_unlock_upload(sid);wfu_Code_Objects[sid].do_action("askserver_noresult")}};xhr.send(parameters)}}
function wfu_HTML5UploadFile_cont(sid,JSONobj,session_token,unique_upload_id){function sendfile(ind,file,only_check,force_close_connection){ret_status=true;var xhr=wfu_GetHttpRequestObject();var xhr_close_connection=wfu_GetHttpRequestObject();if(xhr==null||xhr_close_connection==null)return;var fd=null;var fd_close_connection=null;try{var fd=new FormData;var fd_close_connection=new FormData}catch(e){}if(fd==null||fd_close_connection==null)return;fd.append("action","wfu_ajax_action");fd.append("wfu_uploader_nonce",
document.getElementById("wfu_uploader_nonce_"+sid).value);if(!only_check)fd.append("uploadedfile_"+sid+suffice,file);fd.append("uploadedfile_"+sid+"_index",ind);fd.append("uploadedfile_"+sid+"_name",wfu_plugin_encode_string(farr[ind].name));fd.append("uploadedfile_"+sid+"_size",farr[ind].size);fd.append("uniqueuploadid_"+sid,unique_upload_id);fd.append("params_index",JSONobj.params_index);fd.append("subdir_sel_index",subdir_sel_index);if(only_check)fd.append("only_check","1");else fd.append("only_check",
"0");fd.append("session_token",session_token);var other_params=wfu_Code_Objects[sid].apply_filters("upload_pass_params",{},"ajax");for(var prop in other_params)if(other_params.hasOwnProperty(prop))fd.append(prop,other_params[prop]);var userdata_count=wfu_get_userdata_count(sid);for(var ii=0;ii<userdata_count;ii++)fd.append("hiddeninput_"+sid+"_userdata_"+ii,document.getElementById("hiddeninput_"+sid+"_userdata_"+ii).value);wfu_initialize_fileupload_xhr(xhr,sid,session_token,unique_upload_id,JSONobj,
ind,farr[ind].name);xhr.loading=true;if(!only_check){xhr.size=file.size;xhr.totalsize=farr[ind].size}if(force_close_connection){fd_close_connection.append("action","wfu_ajax_action");fd_close_connection.append("wfu_uploader_nonce",document.getElementById("wfu_uploader_nonce_"+sid).value);fd_close_connection.append("params_index",JSONobj.params_index);fd_close_connection.append("session_token",session_token);fd_close_connection.append("force_connection_close","1");xhr_close_connection.open("POST",
GlobalData.consts.ajax_url,false);try{xhr_close_connection.send(fd_close_connection)}catch(err){}ret_status=xhr_close_connection.responseText.indexOf("success")>-1}if(ret_status)if(!only_check){xhr.upload.xhr=xhr;xhr.upload.dummy=1;xhr.upload.addEventListener("loadstart",wfu_loadStart,false);xhr.upload.addEventListener("progress",new Function("evt","wfu_uploadProgress(evt, "+sid+", "+xhr.xhrid+", "+JSONobj.debugmode+");"),false);xhr.addEventListener("load",wfu_uploadComplete,false);xhr.addEventListener("error",
new Function("evt","wfu_uploadFailed(evt, "+JSONobj.debugmode+");"),false);xhr.addEventListener("abort",wfu_uploadCanceled,false);xhr.open("POST",GlobalData.consts.ajax_url,true);xhr.send(fd)}else{xhr.addEventListener("load",function(evt){evt={target:{responseText:evt.target.responseText,shortcode_id:sid,return_status:true}};var file_status=wfu_uploadComplete.call(xhr,evt);xhr.file_id=0;ret_status=file_status=="success"||file_status=="warning";if(ret_status)sendfile(ind,file,false,false)},false);
xhr.addEventListener("error",function(evt){return},false);xhr.open("POST",GlobalData.consts.ajax_url,true);xhr.send(fd)}else{var evt={target:{responseText:"",shortcode_id:sid}};wfu_uploadComplete.call(xhr,evt)}inc++;return ret_status}var subdir_sel_index=-1;var sel=document.getElementById("selectsubdir_"+sid);if(sel){var editbox=document.getElementById("selectsubdiredit_"+sid);var editable=editbox.style.display!="none";if(editable)subdir_sel_index=editbox.value;else subdir_sel_index=sel.selectedIndex}var farr=
wfu_get_filelist(sid);var suffice="";GlobalData.UploadInProgressString+="["+unique_upload_id+"]";GlobalData[sid]={};GlobalData[sid].unique_id=unique_upload_id;GlobalData[sid].last=false;GlobalData[sid].files_count=1;GlobalData[sid].files_processed=0;GlobalData[sid].upload_state=0;GlobalData[sid].message="";GlobalData[sid].update_wpfilebase="";GlobalData[sid].redirect_link="";GlobalData[sid].notify_only_filename_list="";GlobalData[sid].notify_target_path_list="";GlobalData[sid].notify_attachment_list=
"";GlobalData[sid].admin_messages={};GlobalData[sid].admin_messages.wpfilebase="";GlobalData[sid].admin_messages.notify="";GlobalData[sid].admin_messages.redirect="";GlobalData[sid].admin_messages.debug="";GlobalData[sid].admin_messages.other="";GlobalData[sid].errors={};GlobalData[sid].errors.wpfilebase="";GlobalData[sid].errors.notify="";GlobalData[sid].errors.redirect="";GlobalData[sid].xhrs=Array();GlobalData[sid].metricstotal={size:farr[0].size,loaded:0,progress_pos:0};GlobalData[sid].metrics=
[{size:farr[0].size,loaded:0,progress_pos:0}];wfu_show_simple_progressbar(JSONobj.shortcode_id,"progressive");wfu_attach_cancel_event(sid,session_token,unique_upload_id,JSONobj);var Params=wfu_Initialize_Params();Params.general.shortcode_id=sid;Params.general.unique_id=unique_upload_id;wfu_ProcessUploadComplete(sid,0,Params,unique_upload_id,JSONobj.params_index,session_token,"",["false","","false"]);var inc=0;var ret_status=true;var i=0;var fprops=[];sendfile(i,farr[i],true,false)}
function wfu_initialize_fileupload_xhr(xhr,sid,session_token,unique_upload_id,JSONobj,file_ind,filename){var xhrid=file_ind>=0?GlobalData[sid].xhrs.push(xhr)-1:-1;var d=new Date;xhr.xhrid=xhrid;xhr.shortcode_id=sid;xhr.requesttype=file_ind>=0?"fileupload":"email";xhr.file_id=file_ind+1;xhr.size=0;xhr.totalsize=0;xhr.loading=false;xhr.deltasize=0;xhr.deltaloaded=0;xhr.sizeloaded=0;xhr.aborted=false;xhr.unique_id=unique_upload_id;xhr.params_index=JSONobj.params_index;xhr.session_token=session_token;
xhr.debugmode=JSONobj.debugmode;xhr.is_admin=JSONobj.is_admin;xhr.start_time=d.getTime();xhr.end_time=xhr.start_time;xhr.finish_time=xhr.start_time+parseInt(GlobalData.consts.max_time_limit)*1E3;xhr.fail_colors=JSONobj.fail_colors;xhr.error_message_header=JSONobj.error_header.replace(/%username%/g,"no data");xhr.error_message_header=xhr.error_message_header.replace(/%useremail%/g,"no data");xhr.error_message_header=xhr.error_message_header.replace(/%filename%/g,filename);xhr.error_message_header=
xhr.error_message_header.replace(/%filepath%/g,filename);xhr.error_message_failed=GlobalData.consts.message_failed;xhr.error_message_cancelled=GlobalData.consts.message_cancelled;xhr.error_adminmessage_unknown=GlobalData.consts.adminmessage_unknown.replace(/%username%/g,"no data");xhr.error_adminmessage_unknown=xhr.error_adminmessage_unknown.replace(/%useremail%/g,"no data");xhr.error_adminmessage_unknown=xhr.error_adminmessage_unknown.replace(/%filename%/g,filename);xhr.error_adminmessage_unknown=
xhr.error_adminmessage_unknown.replace(/%filepath%/g,filename)}function wfu_get_userdata_count(sid){var fields_count=0;while(document.getElementById("userdata_"+sid+"_"+fields_count))fields_count++;return fields_count}
function wfu_lock_upload(sid){var textbox=document.getElementById("fileName_"+sid);document.getElementById("input_"+sid).disabled=true;document.getElementById("upfile_"+sid).disabled=true;wfu_selectsubdir_disable_onoff(sid,true);var upload=document.getElementById("upload_"+sid);if(upload)upload.disabled=true;var userdata_count=wfu_get_userdata_count(sid);for(var i=0;i<userdata_count;i++)window["userdata_"+sid+"_codes_"+i].lock(document.getElementById("userdata_"+sid+"_field_"+i));wfu_Code_Objects[sid].do_action("lock_upload")}
function wfu_unlock_upload(sid){var textbox=document.getElementById("fileName_"+sid);document.getElementById("input_"+sid).disabled=false;document.getElementById("upfile_"+sid).disabled=false;wfu_selectsubdir_disable_onoff(sid,false);var upload=document.getElementById("upload_"+sid);if(upload)upload.disabled=false;var userdata_count=wfu_get_userdata_count(sid);for(var i=0;i<userdata_count;i++)window["userdata_"+sid+"_codes_"+i].unlock(document.getElementById("userdata_"+sid+"_field_"+i));wfu_Code_Objects[sid].do_action("unlock_upload")}
function wfu_clear_files(sid){document.getElementById("uploadform_"+sid).reset();var inputfile=document.getElementById("upfile_"+sid);if(typeof inputfile.filearray!="undefined"){inputfile.filearray.length=0;inputfile.filearrayprops.length=0}var textbox=document.getElementById("fileName_"+sid);if(textbox){textbox.value="";textbox.className="file_input_textbox"}}
function wfu_clear(sid){wfu_clear_files(sid);var subdir=document.getElementById("selectsubdir_"+sid);if(subdir){var editbox=document.getElementById("selectsubdiredit_"+sid);var editable=editbox.style.display!="none";if(!editable){subdir.options[0].style.display="block";subdir.selectedIndex=parseInt(document.getElementById("selectsubdirdefault_"+sid).value);if(subdir.selectedIndex<0)subdir.selectedIndex=0}else{subdir.selectedIndex=-1;editbox.value=""}}var userdata_count=wfu_get_userdata_count(sid);
for(var i=0;i<userdata_count;i++)window["userdata_"+sid+"_codes_"+i].reset(document.getElementById("userdata_"+sid+"_field_"+i),document.getElementById("hiddeninput_"+sid+"_userdata_"+i));wfu_Code_Objects[sid].do_action("clear_upload")}
function wfu_reset_message(sid){var message_table=document.getElementById("wfu_messageblock_"+sid);if(message_table){document.getElementById("wfu_messageblock_header_"+sid).style.display="";var header_container=document.getElementById("wfu_messageblock_header_"+sid+"_container");if(UploadStates[sid])header_container.innerHTML=UploadStates[sid]["State0"];document.getElementById("wfu_messageblock_header_"+sid+"_state").value="none";document.getElementById("wfu_messageblock_arrow_"+sid).style.display=
"none";header_container.colSpan=3;document.getElementById("wfu_messageblock_subheader_"+sid+"_messagelabel").innerHTML="";document.getElementById("wfu_messageblock_subheader_"+sid+"_adminmessagelabel").innerHTML="";document.getElementById("wfu_messageblock_subheader_"+sid).style.display="none";document.getElementById("wfu_messageblock_subheader_"+sid+"_message").style.display="none";document.getElementById("wfu_messageblock_subheader_"+sid+"_adminmessage").style.display="none";var file_array=wfu_get_file_ids(sid);
for(var i=1;i<=file_array.length;i++){message_table.tBodies[0].removeChild(document.getElementById("wfu_messageblock_"+sid+"_"+i));message_table.tBodies[0].removeChild(document.getElementById("wfu_messageblock_subheader_"+sid+"_"+i))}}}
function wfu_show_simple_progressbar(sid,effect){var bar=document.getElementById("progressbar_"+sid+"_animation");var barsafe=document.getElementById("progressbar_"+sid+"_imagesafe");if(bar){if(effect=="progressive"){bar.style.width="0%";bar.className="file_progress_progressive";barsafe.style.display="none";bar.style.display="block"}else if(wfu_BrowserCaps.supportsAnimation){bar.style.width="25%";bar.className="file_progress_shuffle";barsafe.style.display="none";bar.style.display="block"}else{bar.style.width=
"0%";bar.className="file_progress_noanimation";bar.style.display="none";barsafe.style.display="block"}document.getElementById("wordpress_file_upload_progressbar_"+sid).style.display="block"}}
function wfu_hide_simple_progressbar(sid){var bar=document.getElementById("progressbar_"+sid+"_animation");var barsafe=document.getElementById("progressbar_"+sid+"_imagesafe");if(bar){document.getElementById("wordpress_file_upload_progressbar_"+sid).style.display="none";bar.style.width="0%";bar.className="file_progress_noanimation";barsafe.style.display="none";bar.style.display="block"}}
function wfu_invoke_shortcode_editor(sid,postid,posthash,tag){var buttons=document.getElementsByTagName("BUTTON");var same=0;var obj=null;for(var i=0;i<buttons.length;i++)if(buttons[i].parentNode)if(buttons[i].parentNode.id==tag+"_editor_"+sid){obj=buttons[i];same++}if(same==0)return;if(same>1){alert(GlobalData.consts.same_pluginid);return}var xhr=wfu_GetHttpRequestObject();if(xhr==null)return;obj.parentNode.style.display="none";document.getElementById(tag+"_overlay_"+sid).style.display="block";var url=
GlobalData.consts.ajax_url;params=new Array(6);params[0]=new Array(2);params[0][0]="action";params[0][1]="wfu_ajax_action_edit_shortcode";params[1]=new Array(2);params[1][0]="upload_id";params[1][1]=sid;params[2]=new Array(2);params[2][0]="post_id";params[2][1]=postid;params[3]=new Array(2);params[3][0]="post_hash";params[3][1]=posthash;params[4]=new Array(2);params[4][0]="shortcode_tag";params[4][1]=tag;params[5]=new Array(2);params[5][0]="widget_id";params[5][1]=document.getElementById(tag+"_"+
sid+"_widgetid")?document.getElementById(tag+"_"+sid+"_widgetid").value:"";var parameters="";for(var i=0;i<params.length;i++)parameters+=(i>0?"&":"")+params[i][0]+"="+encodeURI(params[i][1]);xhr.open("POST",url,true);xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhr.onreadystatechange=function(){if(xhr.readyState==4)if(xhr.status==200){document.getElementById(tag+"_overlay_"+sid).style.display="none";obj.parentNode.removeAttribute("style");var start_text="wfu_edit_shortcode:";
var pos=xhr.responseText.indexOf(start_text);if(pos==-1)pos=xhr.responseText.length;var messages=xhr.responseText.substr(0,pos);var response=xhr.responseText.substr(pos+start_text.length,xhr.responseText.length-pos-start_text.length);pos=response.indexOf(":");var txt_header=response.substr(0,pos);txt_value=response.substr(pos+1,response.length-pos-1);if(txt_header=="success"){var editor_window=window.open(wfu_plugin_decode_string(txt_value),"_blank");if(editor_window)editor_window.plugin_window=window;
else alert(GlobalData.consts.enable_popups)}else if(txt_header=="check_page_obsolete")alert(txt_value)}};xhr.send(parameters)}
wfu_initialize_webcam=function(sid,mode,audiocapture,videowidth,videoheight,videoaspectratio,videoframerate,camerafacing,maxrecordtime){if(typeof wfu_parse_video_width=="undefined")wfu_parse_video_width=function(videowidth){var vw=parseInt(videowidth);if(vw>0){this.empty=false;this.video.width=vw}};if(typeof wfu_parse_video_height=="undefined")wfu_parse_video_height=function(videoheight){var vh=parseInt(videoheight);if(vh>0){this.empty=false;this.video.height=vh}};if(typeof wfu_parse_video_aspectratio==
"undefined")wfu_parse_video_aspectratio=function(videoaspectratio){var ar=parseFloat(videoaspectratio);if(ar>0){this.empty=false;this.video.aspectRatio=ar}};if(typeof wfu_parse_video_framerate=="undefined")wfu_parse_video_framerate=function(videoframerate){var fr=parseFloat(videoframerate);if(fr>0){this.empty=false;this.video.frameRate=fr}};if(typeof wfu_parse_video_facingmode=="undefined")wfu_parse_video_facingmode=function(camerafacing){var cf=camerafacing=="front"?"user":camerafacing=="back"?"environment":
"";if(cf!=""){this.empty=false;this.video.facingMode=cf}};var video_settings={empty:true,video:{}};wfu_parse_video_width.call(video_settings,videowidth);wfu_parse_video_height.call(video_settings,videoheight);wfu_parse_video_aspectratio.call(video_settings,videoaspectratio);wfu_parse_video_framerate.call(video_settings,videoframerate);wfu_parse_video_facingmode.call(video_settings,camerafacing);var WebcamProps={mode:mode,audio:audiocapture=="true",video:video_settings.empty?true:video_settings.video,
maxrecordtime:maxrecordtime};window["wfu_webcam_props_"+sid]=WebcamProps;wfu_reinitialize_webcam(sid)};
wfu_reinitialize_webcam=function(sid){window["wfu_webcam_props_"+sid].active=true;window["wfu_webcam_props_"+sid].width=0;window["wfu_webcam_props_"+sid].width=0;window["wfu_webcam_props_"+sid].timeStart=0;window["wfu_webcam_props_"+sid].duration=0;window["wfu_webcam_props_"+sid].counting=false;window["wfu_webcam_props_"+sid].stream=null;window["wfu_webcam_props_"+sid].media=null;window["wfu_webcam_props_"+sid].blobs=null;window["wfu_webcam_props_"+sid].playing=false;var WebcamProps=window["wfu_webcam_props_"+
sid];var video=document.getElementById("webcam_"+sid+"_box");var webcamoff=document.getElementById("webcam_"+sid+"_webcamoff");webcamoff.style.display="none";video.style.display="block";var constraints={audio:WebcamProps.audio,video:WebcamProps.video};if(typeof Promise=="undefined"){Promise=function(mainCallback){this.mainCallback=mainCallback;this.then=function(successCallback){this.successCallback=successCallback;return this};this["catch"]=function(errorCallback){mainCallback(this.successCallback,
errorCallback)}};PromiseRejected=function(error){this.then=function(successCallback){return this};this["catch"]=function(errorCallback){errorCallback(error)}};Promise.reject=function(error){return new PromiseRejected(error)}}var promisifiedOldGUM=function(constraints,successCallback,errorCallback){var getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;if(!getUserMedia||typeof MediaRecorder=="undefined")return Promise.reject(new Error("getUserMedia is not implemented in this browser"));
return new Promise(function(successCallback,errorCallback){getUserMedia.call(navigator,constraints,successCallback,errorCallback)})};if(navigator.mediaDevices===undefined)navigator.mediaDevices={};if(navigator.mediaDevices.getUserMedia===undefined)navigator.mediaDevices.getUserMedia=promisifiedOldGUM;navigator.mediaDevices.getUserMedia(constraints).then(function(stream){window["wfu_webcam_props_"+sid].stream=stream;video.autoplay=true;video.ontimeupdate=null;video.onerror=null;video.onloadeddata=
function(e){wfu_webcam_init_callback(sid)};video.src=window.URL.createObjectURL(stream);wfu_initialize_webcam_nav(sid,WebcamProps.mode)})["catch"](function(e){console.log("Video not supported!",e);document.getElementById("webcam_"+sid+"_inner").className="wfu_file_webcam_inner wfu_webcam_notsupported"})};
wfu_webcam_init_callback=function(sid){var container=document.getElementById("webcam_"+sid+"_inner");var video=document.getElementById("webcam_"+sid+"_box");window["wfu_webcam_props_"+sid].width=video.videoWidth;window["wfu_webcam_props_"+sid].height=video.videoHeight;var imgdata='<svg xmlns="http://www.w3.org/2000/svg" width="'+video.videoWidth+'" height="'+video.videoHeight+'"></svg>';var imgblob=new Blob([imgdata],{type:"image/svg+xml;charset=utf-8"});var img=document.getElementById("webcam_"+
sid+"_webcamoff_img");img.src=window.URL.createObjectURL(imgblob);img.style.width=container.clientWidth+"px";img.style.height=container.clientHeight+"px"};
wfu_initialize_webcam_nav=function(sid,mode){if(typeof SVGInjector=="undefined")!function(t,e){function r(t){t=t.split(" ");for(var e={},r=t.length,n=[];r--;)e.hasOwnProperty(t[r])||(e[t[r]]=1,n.unshift(t[r]));return n.join(" ")}var n="file:"===t.location.protocol,i=e.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1"),o=Array.prototype.forEach||function(t,e){if(void 0===this||null===this||"function"!=typeof t)throw new TypeError;var r,n=this.length>>>0;for(r=0;n>
r;++r)r in this&&t.call(e,this[r],r,this)},a={},l=0,s=[],u=[],c={},f=function(t){return t.cloneNode(!0)},p=function(t,e){u[t]=u[t]||[],u[t].push(e)},d=function(t){for(var e=0,r=u[t].length;r>e;e++)!function(e){setTimeout(function(){u[t][e](f(a[t]))},0)}(e)},v=function(e,r){if(void 0!==a[e])a[e]instanceof SVGSVGElement?r(f(a[e])):p(e,r);else{if(!t.XMLHttpRequest)return r("Browser does not support XMLHttpRequest"),!1;a[e]={},p(e,r);var i=new XMLHttpRequest;i.onreadystatechange=function(){if(4===i.readyState){if(404===
i.status||null===i.responseXML)return r("Unable to load SVG file: "+e),n&&r("Note: SVG injection ajax calls do not work locally without adjusting security setting in your browser. Or consider using a local webserver."),r(),!1;if(!(200===i.status||n&&0===i.status))return r("There was a problem injecting the SVG: "+i.status+" "+i.statusText),!1;if(i.responseXML instanceof Document)a[e]=i.responseXML.documentElement;else if(DOMParser&&DOMParser instanceof Function){var t;try{var o=new DOMParser;t=o.parseFromString(i.responseText,
"text/xml")}catch(l$4){t=void 0}if(!t||t.getElementsByTagName("parsererror").length)return r("Unable to parse SVG file: "+e),!1;a[e]=t.documentElement}d(e)}},i.open("GET",e),i.overrideMimeType&&i.overrideMimeType("text/xml"),i.send()}},h=function(e,n,a,u){var f=e.getAttribute("data-src")||e.getAttribute("src");if(!/\.svg/i.test(f))return void u("Attempted to inject a file with a non-svg extension: "+f);if(!i){var p=e.getAttribute("data-fallback")||e.getAttribute("data-png");return void(p?(e.setAttribute("src",
p),u(null)):a?(e.setAttribute("src",a+"/"+f.split("/").pop().replace(".svg",".png")),u(null)):u("This browser does not support SVG and no PNG fallback was defined."))}-1===s.indexOf(e)&&(s.push(e),e.setAttribute("src",""),v(f,function(i){if("undefined"==typeof i||"string"==typeof i)return u(i),!1;var a=e.getAttribute("id");a&&i.setAttribute("id",a);var p=e.getAttribute("title");p&&i.setAttribute("title",p);var d=[].concat(i.getAttribute("class")||[],"injected-svg",e.getAttribute("class")||[]).join(" ");
i.setAttribute("class",r(d));var v=e.getAttribute("style");v&&i.setAttribute("style",v);var h=[].filter.call(e.attributes,function(t){return/^data-\w[\w\-]*$/.test(t.name)});o.call(h,function(t){t.name&&t.value&&i.setAttribute(t.name,t.value)});var g,m,b,y,A,w={clipPath:["clip-path"],"color-profile":["color-profile"],cursor:["cursor"],filter:["filter"],linearGradient:["fill","stroke"],marker:["marker","marker-start","marker-mid","marker-end"],mask:["mask"],pattern:["fill","stroke"],radialGradient:["fill",
"stroke"]};Object.keys(w).forEach(function(t){g=t,b=w[t],m=i.querySelectorAll("defs "+g+"[id]");for(var e=0,r=m.length;r>e;e++){y=m[e].id,A=y+"-"+l;var n;o.call(b,function(t){n=i.querySelectorAll("["+t+'*="'+y+'"]');for(var e=0,r=n.length;r>e;e++)n[e].setAttribute(t,"url(#"+A+")")}),m[e].id=A}}),i.removeAttribute("xmlns:a");for(var x,S,k=i.querySelectorAll("script"),j=[],G=0,T=k.length;T>G;G++)S=k[G].getAttribute("type"),S&&"application/ecmascript"!==S&&"application/javascript"!==S||(x=k[G].innerText||
k[G].textContent,j.push(x),i.removeChild(k[G]));if(j.length>0&&("always"===n||"once"===n&&!c[f])){for(var M=0,V=j.length;V>M;M++)(new Function(j[M]))(t);c[f]=!0}var E=i.querySelectorAll("style");o.call(E,function(t){t.textContent+=""}),e.parentNode.replaceChild(i,e),delete s[s.indexOf(e)],e=null,l++,u(i)}))},g=function(t,e,r){e=e||{};var n=e.evalScripts||"always",i=e.pngFallback||!1,a=e.each;if(void 0!==t.length){var l=0;o.call(t,function(e){h(e,n,i,function(e){a&&"function"==typeof a&&a(e),r&&t.length===
++l&&r(l)})})}else t?h(t,n,i,function(e){a&&"function"==typeof a&&a(e),r&&r(1),t=null}):r&&r(0)};"object"==typeof module&&"object"==typeof module.exports?module.exports=exports=g:"function"==typeof define&&define.amd?define(function(){return g}):"object"==typeof t&&(t.SVGInjector=g)}(window,document);if(document.getElementById("webcam_"+sid+"_btns_converted").value!="1"){SVGInjector(document.getElementById("webcam_"+sid+"_btns"));document.getElementById("webcam_"+sid+"_btns_converted").value="1"}if(mode==
"capture video")wfu_webcam_set_nav_status(sid,"idle_only_video");else if(mode=="take photos")wfu_webcam_set_nav_status(sid,"idle_only_pictures");else if(mode=="both")wfu_webcam_set_nav_status(sid,"idle_video_and_pictures");else wfu_webcam_set_nav_status(sid,"idle_only_video")};
wfu_webcam_set_nav_status=function(sid,status){var onoff=document.getElementById("webcam_"+sid+"_btn_onoff");var nav=document.getElementById("webcam_"+sid+"_nav");var vid=document.getElementById("webcam_"+sid+"_btn_video");var rec=document.getElementById("webcam_"+sid+"_btn_record");var play=document.getElementById("webcam_"+sid+"_btn_play");var stop=document.getElementById("webcam_"+sid+"_btn_stop");var pause=document.getElementById("webcam_"+sid+"_btn_pause");var pos=document.getElementById("webcam_"+
sid+"_btn_pos");var back=document.getElementById("webcam_"+sid+"_btn_back");var fwd=document.getElementById("webcam_"+sid+"_btn_fwd");var tim=document.getElementById("webcam_"+sid+"_btn_time");var pic=document.getElementById("webcam_"+sid+"_btn_picture");var screenshot=document.getElementById("webcam_"+sid+"_screenshot");onoff.style.display="block";if(status=="hidden")nav.style.display="none";else if(status=="recording"){nav.removeAttribute("style");nav.className="wfu_file_webcam_nav wfu_recording";
vid.style.display="none";rec.style.display="block";rec.style.visibility="visible";rec.setAttribute("class","wfu_file_webcam_btn wfu_file_webcam_btn_record wfu_recording");stop.style.display="block";stop.style.visibility="visible";play.style.display="block";play.style.visibility="hidden";pause.style.display="block";pause.style.visibility="hidden";pos.style.display="block";pos.style.visibility="hidden";back.style.display="block";back.style.visibility="hidden";fwd.style.display="block";fwd.style.visibility=
"hidden";tim.style.display="block";tim.style.visibility="visible";pic.style.display="none";screenshot.style.display="none"}else if(status=="after_recording"){nav.removeAttribute("style");nav.className="wfu_file_webcam_nav wfu_stream_ready";vid.style.display="block";vid.setAttribute("class","wfu_file_webcam_btn wfu_file_webcam_btn_video");rec.style.display="none";stop.style.display="block";stop.style.visibility="hidden";play.style.display="block";play.style.visibility="hidden";pause.style.display=
"block";pause.style.visibility="hidden";pos.style.display="block";pos.style.visibility="hidden";back.style.display="block";back.style.visibility="hidden";fwd.style.display="block";fwd.style.visibility="hidden";tim.style.display="block";tim.style.visibility="hidden";pic.style.display="none";screenshot.style.display="block"}else if(status=="ready_playback"){nav.removeAttribute("style");nav.className="wfu_file_webcam_nav wfu_stream_ready";vid.style.display="block";vid.setAttribute("class","wfu_file_webcam_btn wfu_file_webcam_btn_video");
rec.style.display="none";stop.style.display="block";stop.style.visibility="hidden";play.style.display="block";play.style.visibility="visible";play.setAttribute("class","wfu_file_webcam_btn wfu_file_webcam_btn_play");pause.style.display="block";pause.style.visibility="visible";pause.setAttribute("class","wfu_file_webcam_btn_disabled wfu_file_webcam_btn_pause_disabled");pos.style.display="block";pos.style.visibility="visible";back.style.display="block";back.style.visibility="visible";fwd.style.display=
"block";fwd.style.visibility="visible";tim.style.display="block";tim.style.visibility="visible";pic.style.display="none";screenshot.style.display="none"}else if(status=="after_screenshot"){nav.removeAttribute("style");nav.className="wfu_file_webcam_nav wfu_stream_ready";vid.style.display="block";vid.setAttribute("class","wfu_file_webcam_btn wfu_file_webcam_btn_video");rec.style.display="none";stop.style.display="block";stop.style.visibility="hidden";play.style.display="block";play.style.visibility=
"hidden";pause.style.display="block";pause.style.visibility="hidden";pos.style.display="block";pos.style.visibility="hidden";back.style.display="block";back.style.visibility="hidden";fwd.style.display="block";fwd.style.visibility="hidden";tim.style.display="block";tim.style.visibility="hidden";pic.style.display="none";screenshot.style.display="block"}else if(status=="playing"){nav.removeAttribute("style");nav.className="wfu_file_webcam_nav wfu_stream_ready";vid.style.display="block";vid.setAttribute("class",
"wfu_file_webcam_btn_disabled wfu_file_webcam_btn_video_disabled");rec.style.display="none";stop.style.display="block";stop.style.visibility="hidden";play.style.display="block";play.style.visibility="visible";play.setAttribute("class","wfu_file_webcam_btn_disabled wfu_file_webcam_btn_play_disabled");pause.style.display="block";pause.style.visibility="visible";pause.setAttribute("class","wfu_file_webcam_btn wfu_file_webcam_btn_pause");pos.style.display="block";pos.style.visibility="visible";back.style.display=
"block";back.style.visibility="visible";fwd.style.display="block";fwd.style.visibility="visible";tim.style.display="block";tim.style.visibility="visible";pic.style.display="none";screenshot.style.display="none"}else{nav.removeAttribute("style");nav.className="wfu_file_webcam_nav wfu_rec_ready";vid.style.display="none";rec.style.display="none";stop.style.display="none";play.style.display="none";pause.style.display="none";pos.style.display="none";back.style.display="none";fwd.style.display="none";tim.style.display=
"none";pic.style.display="none";screenshot.style.display="none";if(status=="idle_only_video"||status=="idle_video_and_pictures"){rec.style.display="block";rec.setAttribute("class","wfu_file_webcam_btn wfu_file_webcam_btn_record")}if(status=="idle_only_pictures"||status=="idle_video_and_pictures")pic.style.display="block"}};
wfu_webcam_counter_status=function(sid,action){if(action=="start"){var d=new Date;window["wfu_webcam_props_"+sid].duration=0;window["wfu_webcam_props_"+sid].timeStart=d.getTime()/1E3;window["wfu_webcam_props_"+sid].counting=true;wfu_webcam_update_counter(sid)}else{var d=new Date;window["wfu_webcam_props_"+sid].duration=d.getTime()/1E3-window["wfu_webcam_props_"+sid].timeStart;window["wfu_webcam_props_"+sid].counting=false}};
wfu_webcam_update_counter=function(sid){if(window["wfu_webcam_props_"+sid].counting){var d=new Date;var dif=d.getTime()/1E3-window["wfu_webcam_props_"+sid].timeStart;wfu_webcam_update_timer(sid,dif);setTimeout(function(){wfu_webcam_update_counter(sid)},100)}};
wfu_webcam_update_timer=function(sid,time){var hours=Math.floor(time/3600);time-=hours*3600;var minutes=Math.floor(time/60);time-=minutes*60;var secs=Math.floor(time);var msecs=(time-Math.floor(time))*1E3;document.getElementById("webcam_"+sid+"_btn_time_label").innerHTML=(hours>0?hours+":":"")+(minutes<10?"0":"")+minutes+":"+(secs<10?"0":"")+secs};
wfu_webcam_onoff=function(sid){if(window["wfu_webcam_props_"+sid].active){var container=document.getElementById("webcam_"+sid+"_inner");var video=document.getElementById("webcam_"+sid+"_box");var webcamoff=document.getElementById("webcam_"+sid+"_webcamoff");var img=document.getElementById("webcam_"+sid+"_webcamoff_img");img.style.width=container.clientWidth+"px";img.style.height=container.clientHeight+"px";video.pause();video.src="";video.load();if(window["wfu_webcam_props_"+sid].stream&&window["wfu_webcam_props_"+
sid].stream.stop)window["wfu_webcam_props_"+sid].stream.stop();window["wfu_webcam_props_"+sid].stream=null;window["wfu_webcam_props_"+sid].media=null;window["wfu_webcam_props_"+sid].blobs=null;wfu_webcam_set_nav_status(sid,"hidden");video.style.display="none";document.getElementById("webcam_"+sid+"_screenshot").src="";webcamoff.style.display="block";window["wfu_webcam_props_"+sid].active=false}else wfu_reinitialize_webcam(sid);wfu_selectbutton_clicked(sid)};
wfu_webcam_golive=function(sid){if(window["wfu_webcam_props_"+sid].playing)return;wfu_reinitialize_webcam(sid);wfu_add_files(sid,[],false);wfu_selectbutton_clicked(sid);wfu_update_uploadbutton_status(sid)};
wfu_webcam_start_rec=function(sid){if(window["wfu_webcam_props_"+sid].media&&window["wfu_webcam_props_"+sid].media.state&&window["wfu_webcam_props_"+sid].media.state=="recording")return;try{window["wfu_webcam_props_"+sid].media=new MediaRecorder(window["wfu_webcam_props_"+sid].stream)}catch(err){alert(document.getElementById("webcam_"+sid+"_video_notsupported").value);return}window["wfu_webcam_props_"+sid].blobs=[];window["wfu_webcam_props_"+sid].media.ondataavailable=function(e){var d=new Date;var dif=
d.getTime()/1E3-window["wfu_webcam_props_"+sid].timeStart;if(window["wfu_webcam_props_"+sid].maxrecordtime==-1||window["wfu_webcam_props_"+sid].maxrecordtime>0&&dif<=window["wfu_webcam_props_"+sid].maxrecordtime){if(e.data&&e.data.size>0)window["wfu_webcam_props_"+sid].blobs.push(e.data)}else wfu_webcam_stop_rec(sid)};wfu_webcam_set_nav_status(sid,"recording");wfu_webcam_counter_status(sid,"start");window["wfu_webcam_props_"+sid].media.onstop=function(e){wfu_webcam_counter_status(sid,"stop");wfu_webcam_set_nav_status(sid,
"after_recording");wfu_webcam_onstop(e,sid)};window["wfu_webcam_props_"+sid].media.start(10)};wfu_webcam_stop_rec=function(sid){window["wfu_webcam_props_"+sid].media.stop()};
wfu_webcam_onstop=function(e,sid){if(window["wfu_webcam_props_"+sid].blobs.length==0){alert(document.getElementById("webcam_"+sid+"_video_nothingrecorded").value);wfu_webcam_golive(sid)}else{var video=document.getElementById("webcam_"+sid+"_box");var canvas=document.getElementById("webcam_"+sid+"_canvas");var screenshot=document.getElementById("webcam_"+sid+"_screenshot");if(window["wfu_webcam_props_"+sid].stream){canvas.width=video.clientWidth;canvas.height=video.clientHeight;var ctx=canvas.getContext("2d");
ctx.drawImage(video,0,0,video.clientWidth,video.clientHeight);screenshot.src=canvas.toDataURL("image/webp")}var superBuffer=new Blob(window["wfu_webcam_props_"+sid].blobs,{type:"video/mp4"});video.autoplay=false;video.ontimeupdate=function(e){wfu_webcam_update_pos(sid)};video.onended=function(e){wfu_webcam_ended(sid)};video.onloadeddata=function(e){if(video.readyState>=2)wfu_webcam_set_nav_status(sid,"ready_playback")};video.onerror=function(e){video.onloadeddata=null;video.src=window.URL.createObjectURL(window["wfu_webcam_props_"+
sid].stream)};video.src=window.URL.createObjectURL(superBuffer);superBuffer.name="video.mp4";wfu_add_files(sid,[{file:superBuffer,props:{}}],false);wfu_update_uploadbutton_status(sid)}};wfu_webcam_play=function(sid){if(window["wfu_webcam_props_"+sid].playing)return;var video=document.getElementById("webcam_"+sid+"_box");wfu_webcam_set_nav_status(sid,"playing");window["wfu_webcam_props_"+sid].playing=true;video.play()};
wfu_webcam_ended=function(sid){var video=document.getElementById("webcam_"+sid+"_box");video.src=video.src;wfu_webcam_set_nav_status(sid,"ready_playback");window["wfu_webcam_props_"+sid].playing=false};wfu_webcam_pause=function(sid){var video=document.getElementById("webcam_"+sid+"_box");video.pause();wfu_webcam_set_nav_status(sid,"ready_playback");window["wfu_webcam_props_"+sid].playing=false};
wfu_webcam_back=function(sid){var video=document.getElementById("webcam_"+sid+"_box");video.src=video.src;video.currentTime=0};wfu_webcam_fwd=function(sid){var video=document.getElementById("webcam_"+sid+"_box");video.currentTime=isFinite(video.duration)?video.duration:window["wfu_webcam_props_"+sid].duration*2};
wfu_webcam_take_picture=function(sid){var video=document.getElementById("webcam_"+sid+"_box");var canvas=document.getElementById("webcam_"+sid+"_canvas");var screenshot=document.getElementById("webcam_"+sid+"_screenshot");if(window["wfu_webcam_props_"+sid].stream){canvas.width=video.clientWidth;canvas.height=video.clientHeight;var ctx=canvas.getContext("2d");ctx.drawImage(video,0,0,video.clientWidth,video.clientHeight);screenshot.src=canvas.toDataURL("image/webp");wfu_webcam_set_nav_status(sid,"after_screenshot");
if(!window["wfu_toBlob_function_initialized"]){!function(t){var e=t.HTMLCanvasElement&&t.HTMLCanvasElement.prototype,o=t.Blob&&function(){try{return Boolean(new Blob)}catch(t$5){return!1}}(),n=o&&t.Uint8Array&&function(){try{return 100===(new Blob([new Uint8Array(100)])).size}catch(t$6){return!1}}(),r=t.BlobBuilder||t.WebKitBlobBuilder||t.MozBlobBuilder||t.MSBlobBuilder,a=/^data:((.*?)(;charset=.*?)?)(;base64)?,/,i=(o||r)&&t.atob&&t.ArrayBuffer&&t.Uint8Array&&function(t){var e,i,l,u,b,c,d,B,f;if(e=
t.match(a),!e)throw new Error("invalid data URI");for(i=e[2]?e[1]:"text/plain"+(e[3]||";charset=US-ASCII"),l=!!e[4],u=t.slice(e[0].length),b=l?atob(u):decodeURIComponent(u),c=new ArrayBuffer(b.length),d=new Uint8Array(c),B=0;B<b.length;B+=1)d[B]=b.charCodeAt(B);return o?new Blob([n?d:c],{type:i}):(f=new r,f.append(c),f.getBlob(i))};t.HTMLCanvasElement&&!e.toBlob&&(e.mozGetAsFile?e.toBlob=function(t,o,n){t(n&&e.toDataURL&&i?i(this.toDataURL(o,n)):this.mozGetAsFile("blob",o))}:e.toDataURL&&i&&(e.toBlob=
function(t,e,o){t(i(this.toDataURL(e,o)))})),"function"==typeof define&&define.amd?define(function(){return i}):"object"==typeof module&&module.exports?module.exports=i:t.dataURLtoBlob=i}(window);window["wfu_toBlob_function_initialized"]=true}if(canvas.toBlob)canvas.toBlob(function(blob){blob.name="image.png";wfu_add_files(sid,[{file:blob,props:{}}],false);wfu_update_uploadbutton_status(sid)},"image/png")}};
wfu_webcam_update_pos=function(sid){var video=document.getElementById("webcam_"+sid+"_box");var pointer=document.getElementById("webcam_"+sid+"_btn_pointer");var duration=isFinite(video.duration)?video.duration:window["wfu_webcam_props_"+sid].duration;var pos=Math.round(video.currentTime/duration*100);pointer.style.left=pos+"%";wfu_webcam_update_timer(sid,video.currentTime)};
